config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, skip: [:registrations]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'

  get 'page/:id', to: 'pages#show', as: 'show_page'
  post 'message', to: 'message#create'
  get 'portfolio', to: 'portfolio#index', as: 'portfolio_index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/page_admin.rb
module PageAdmin
  extend ActiveSupport::Concern

  included do
    rails_admin do
      edit do
        field :title
        field :description
        field :body, :ck_editor
      end
      list do
        field :title
        field :slug
        field :description
        field :created_at
        field :updated_at
      end
    end
  end

end

app/models/concerns/portfolio_admin.rb
module PortfolioAdmin
  extend ActiveSupport::Concern

  included do
    rails_admin do
    end
  end

end

app/models/concerns/technology_admin.rb
module TechnologyAdmin
  extend ActiveSupport::Concern

  included do
    rails_admin do
    end
  end

end

app/models/concerns/user_admin.rb
module UserAdmin
  extend ActiveSupport::Concern

  included do
    rails_admin do
      edit do
        field :email
        field :password
        field :password_confirmation
      end
    end
  end

end

app/models/message.rb
class Message < ApplicationRecord
  validates :email, :message, :presence => true
  validates :name, :length => { :minimum => 2, :maximum => 255 }
  validates :message, :length => { :minimum => 3, :maximum => 65535 }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

end

app/models/page.rb
class Page < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, :description, :body, :presence => true
  validates :title, :length => { :minimum => 3, :maximum => 255 }
  validates :body, :length => { :minimum => 3, :maximum => 65535 }
  validates :description, :length => { :minimum => 3, :maximum => 255 }

  include PageAdmin

end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_and_belongs_to_many :technologies
  has_one_attached :preview

  validate :preview_validation

  validates :title, :description, :presence => true
  validates :url, :format => { :with => URI::regexp(%w(http https)) }

  def preview_validation
    if preview.attached?
      if !preview.blob.content_type.eql?('image/jpeg') && !preview.blob.content_type.eql?('image/png')
        preview.purge
        errors[:base] << 'Preview wrong format'
      elsif preview.blob.byte_size > 1000000
        preview.purge
        errors[:base] << 'Preview too big'
      end
    end
  end

end

app/models/social.rb
class Social < ApplicationRecord
  has_one_attached :icon

  validate :icon_validation
  validates :title, :url, :icon, :presence => true
  validates :url, :format => { :with => URI::regexp(%w(http https)) }

  def icon_validation
    if icon.attached?
      if !icon.blob.content_type.eql?('image/svg+xml')
        icon.purge
        errors[:base] << 'Icon wrong format'
      end
    end

  end
end

app/models/technology.rb
class Technology < ApplicationRecord
  include TechnologyAdmin

  has_and_belongs_to_many :portfolios

  validates :title, :icon_url, :presence => false
  validates :icon_url, :format => { :with => URI::regexp(%w(http https)) }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include UserAdmin

  validates :email, :password, :password_confirmation, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include MenuConcern

  before_action :setup_menu

end

app/controllers/concerns/menu_concern.rb
module CvMenu
  class Menu
    def initialize(controller)
      file = File.join(Rails.root, 'config', 'menu.yml')
      if !File.exists?(file)
        raise "File not exists"
      end
      @@config = YAML.load_file file
      @@controller = controller
    end

    def items
      @@config['menu']['items'].each do |item|
        if item['link'].start_with? ':'
          method_name = item['link'].slice 1 .. item['link'].length
          params = method_name.split(' ')
          if params.length == 1
          url = @@controller.send(params[0])
          else
          url = @@controller.send(params[0], params[1])
          end
          yield MenuItem.new item['label'], url, item['turbolinks']
        else
          yield MenuItem.new item['label'], item['link'], item['turbolinks']
        end
      end
    end

  end

  class MenuItem
    def initialize(label, url, turbolinks=true)
      @@label = label
      @@url = url
      @@turbolinks = turbolinks
    end

    def label
      @@label
    end

    def url
      @@url
    end
    
    def turbolinks
      @@turbolinks
    end

  end

end


module MenuConcern
  extend ActiveSupport::Concern

  def setup_menu
    @menu = CvMenu::Menu.new(self)
  end

end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  def create
    puts message_params.inspect
    @message = Message.new(message_params)
    if !@message.save
      render :json => { :errors => @message.errors.full_messages }, :status => 422
    else
      render :json => { :status => 'Ok' }
    end
  end

private
  def message_params
    params.required(:message).permit(:name, :email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action :set_page, only: [:show]

  def home
    @technologies = Technology.order(:title)
    @max_hours = Technology.maximum(:hours).to_f
  end

  def show
  end

  private
  def set_page
    @page = Page.friendly.find(params[:id])
  end

end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index()
    @portfolio_items = Portfolio.includes(:technologies).all.order(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def progress_bar_width(base: base, current: current )
    min_size = 15
    percents = current / base * 100
    percents = percents < min_size ? min_size : percents
  end

  def socials
    Social.all
  end

end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:meta_title) ? yield(:meta_title) : "Remote software developer" %> | Andrei Siearheyeu </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="title" content="<%= content_for?(:meta_title) ? yield(:meta_title) : "Remote software developer" %> | Andrei Siearheyeu">
    <meta name="description" content="<%= content_for?(:meta_description) ? yield(:meta_description) : "Remote software developer PHP, Laravel, Vue.js started at $20 per hour." %>">
    <link rel="icon" href="<%= image_url('favicon.ico') %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="container" id="dev-vue-app">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">
          <img src="<%= asset_url 'logo.svg', type: :image %>" width="96" alt="logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <% @menu.items do |menu_item| %>
            <li class="nav-item <%= 'active' if current_page?(menu_item.url) %>">
              <% if menu_item.turbolinks %>
                <%= link_to menu_item.label, menu_item.url, class: "nav-link" %>
              <% else %>
                <%= link_to menu_item.label, menu_item.url, class: "nav-link", data: { turbolinks: false } %>
              <% end %>  
            </li>
            <% end %>
          </ul>
          <div class="col-sm-3 socials-btn">
              <ul class="navbar-nav">
                <% socials.each do | social | %>
                <li class="nav-item">
                  <a href="<%= social.url %>" target="_blank" rel="nofollow" class="nav-link">
                    <%= image_tag social.icon, alt: social.title %>
                  </a>
                </li>
                <% end %>
              </ul>
          </div>
        </div>
      </nav>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<section class="home-about-me">
  <h1>Hello dear guest!</h1>
  <p>
  My name is Andrey, but you can call me Andrew if it will be comfortable for you.<br/>
  Below you can find information about my experience.<br/>
  Little bit more about me you can find on <a href="<%= show_page_path 'about-me' %>">&quot;About Me&quot; page.</a>
  </p>
  <p>
  Also you can get some information about projects, which I had worked on <a href="<%= portfolio_index_path %>">&quot;Portfolio&quot; page.</a><br/>
  If you not got enough information about me or my experience or you have some questions<br/> 
  please use contact form on <a href="<%= show_page_path 'contact-me' %>">&quot;Contact me&quot; page</a> for send me message.
  </p>
</section>
<div class="row">
  <div class="col-md-6 col-sm-12">
  <h3>Experience in hours</h3>
    <ul class="technology-container">
      <% @technologies.each do | technology | %>
      <li class="technology-item">
        <div class="row">
          <div class="col-lg-4 col-md-4">
            <div class="full-relative">
              <img src="<%= technology.icon_url %>">
              <span class="title"><%= technology.title %></span>
            </div>
          </div>
          <div class="col-lg-8 col-md-8">
            <span class="hours" style="width:<%= progress_bar_width base: @max_hours, current: technology.hours.to_f %>%">
              <%= number_with_delimiter technology.hours %> (h)
            </span>
          </div>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
  <div class="col-sm-12 col-lg-6 col-xl-6 col-md-6">
    <img src="<%= image_url('portrait.jpg') %>" alt="Andrey Sergeev remote software engineer" width="100%">
  </div>
</div>

app/views/pages/show.html.erb
<% content_for(:meta_title) { @page.title } %>
<% content_for(:meta_description) { @page.description } %>
<h1><%= @page.title %></h1>
<div class="row">
  <div class="col-lg-12">
    <%= @page.body.html_safe %>
  </div>
</div>

app/views/portfolio/index.html.erb
<% content_for(:meta_title) { 'Portfolio' } %>
<% content_for(:meta_description) { 'My portfolio with some latest projects' } %>
<h1>Portfolio</h1>
<div class="row">
  <% @portfolio_items.each do | item | %>
  <div class="col-xl-4 col-lg-4 col-md-3 col-sm-6 col-12">
    <div class="card">
      <%= image_tag item.preview.variant(resize: "468x200"), alt: item.title %>
      <div class="card-body">
        <div class="card-title">
        <% if item.url %>
          <h4><a href="<%= item.url %>" target="_blank" rel="nofollow"><%= item.title %></a></h4>
        <% else %>
          <h4><%= item.title %></h4>
        <% end %>  
        </div>

        <div class="card-text">
          <p><%= item.description %></p>
          <div class="portfolio-item-tech-block">
            <ul>
            <% item.technologies.each do | technology | %>
            <li>
              <span class="title"><%= technology.title %></span>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>